# DB setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapi?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security.web: trace  # 시큐리티 관련 로그 남기기

server:
  servlet:
    session:
      tracking-modes: cookie

# file upload path
shop.upload.path: upload